# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/d/systemCProjects/SerDesSystemCProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/d/systemCProjects/SerDesSystemCProject

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/systemCProjects/SerDesSystemCProject/CMakeFiles /mnt/d/systemCProjects/SerDesSystemCProject//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/d/systemCProjects/SerDesSystemCProject/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named serdes_lib

# Build rule for target.
serdes_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 serdes_lib
.PHONY : serdes_lib

# fast build rule for target.
serdes_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/build
.PHONY : serdes_lib/fast

#=============================================================================
# Target rules for targets named ctle_tran_tb

# Build rule for target.
ctle_tran_tb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ctle_tran_tb
.PHONY : ctle_tran_tb

# fast build rule for target.
ctle_tran_tb/fast:
	$(MAKE) $(MAKESILENT) -f tb/CMakeFiles/ctle_tran_tb.dir/build.make tb/CMakeFiles/ctle_tran_tb.dir/build
.PHONY : ctle_tran_tb/fast

#=============================================================================
# Target rules for targets named vga_tran_tb

# Build rule for target.
vga_tran_tb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vga_tran_tb
.PHONY : vga_tran_tb

# fast build rule for target.
vga_tran_tb/fast:
	$(MAKE) $(MAKESILENT) -f tb/CMakeFiles/vga_tran_tb.dir/build.make tb/CMakeFiles/vga_tran_tb.dir/build
.PHONY : vga_tran_tb/fast

#=============================================================================
# Target rules for targets named sampler_tran_tb

# Build rule for target.
sampler_tran_tb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sampler_tran_tb
.PHONY : sampler_tran_tb

# fast build rule for target.
sampler_tran_tb/fast:
	$(MAKE) $(MAKESILENT) -f tb/CMakeFiles/sampler_tran_tb.dir/build.make tb/CMakeFiles/sampler_tran_tb.dir/build
.PHONY : sampler_tran_tb/fast

#=============================================================================
# Target rules for targets named cdr_tran_tb

# Build rule for target.
cdr_tran_tb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cdr_tran_tb
.PHONY : cdr_tran_tb

# fast build rule for target.
cdr_tran_tb/fast:
	$(MAKE) $(MAKESILENT) -f tb/CMakeFiles/cdr_tran_tb.dir/build.make tb/CMakeFiles/cdr_tran_tb.dir/build
.PHONY : cdr_tran_tb/fast

#=============================================================================
# Target rules for targets named wave_gen_tran_tb

# Build rule for target.
wave_gen_tran_tb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wave_gen_tran_tb
.PHONY : wave_gen_tran_tb

# fast build rule for target.
wave_gen_tran_tb/fast:
	$(MAKE) $(MAKESILENT) -f tb/CMakeFiles/wave_gen_tran_tb.dir/build.make tb/CMakeFiles/wave_gen_tran_tb.dir/build
.PHONY : wave_gen_tran_tb/fast

#=============================================================================
# Target rules for targets named channel_sparam_tb

# Build rule for target.
channel_sparam_tb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 channel_sparam_tb
.PHONY : channel_sparam_tb

# fast build rule for target.
channel_sparam_tb/fast:
	$(MAKE) $(MAKESILENT) -f tb/CMakeFiles/channel_sparam_tb.dir/build.make tb/CMakeFiles/channel_sparam_tb.dir/build
.PHONY : channel_sparam_tb/fast

#=============================================================================
# Target rules for targets named nrz_link_tb

# Build rule for target.
nrz_link_tb: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 nrz_link_tb
.PHONY : nrz_link_tb

# fast build rule for target.
nrz_link_tb/fast:
	$(MAKE) $(MAKESILENT) -f tb/CMakeFiles/nrz_link_tb.dir/build.make tb/CMakeFiles/nrz_link_tb.dir/build
.PHONY : nrz_link_tb/fast

src/ams/adaption.o: src/ams/adaption.cpp.o
.PHONY : src/ams/adaption.o

# target to build an object file
src/ams/adaption.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/adaption.cpp.o
.PHONY : src/ams/adaption.cpp.o

src/ams/adaption.i: src/ams/adaption.cpp.i
.PHONY : src/ams/adaption.i

# target to preprocess a source file
src/ams/adaption.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/adaption.cpp.i
.PHONY : src/ams/adaption.cpp.i

src/ams/adaption.s: src/ams/adaption.cpp.s
.PHONY : src/ams/adaption.s

# target to generate assembly for a file
src/ams/adaption.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/adaption.cpp.s
.PHONY : src/ams/adaption.cpp.s

src/ams/channel_sparam.o: src/ams/channel_sparam.cpp.o
.PHONY : src/ams/channel_sparam.o

# target to build an object file
src/ams/channel_sparam.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/channel_sparam.cpp.o
.PHONY : src/ams/channel_sparam.cpp.o

src/ams/channel_sparam.i: src/ams/channel_sparam.cpp.i
.PHONY : src/ams/channel_sparam.i

# target to preprocess a source file
src/ams/channel_sparam.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/channel_sparam.cpp.i
.PHONY : src/ams/channel_sparam.cpp.i

src/ams/channel_sparam.s: src/ams/channel_sparam.cpp.s
.PHONY : src/ams/channel_sparam.s

# target to generate assembly for a file
src/ams/channel_sparam.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/channel_sparam.cpp.s
.PHONY : src/ams/channel_sparam.cpp.s

src/ams/clock_generation.o: src/ams/clock_generation.cpp.o
.PHONY : src/ams/clock_generation.o

# target to build an object file
src/ams/clock_generation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/clock_generation.cpp.o
.PHONY : src/ams/clock_generation.cpp.o

src/ams/clock_generation.i: src/ams/clock_generation.cpp.i
.PHONY : src/ams/clock_generation.i

# target to preprocess a source file
src/ams/clock_generation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/clock_generation.cpp.i
.PHONY : src/ams/clock_generation.cpp.i

src/ams/clock_generation.s: src/ams/clock_generation.cpp.s
.PHONY : src/ams/clock_generation.s

# target to generate assembly for a file
src/ams/clock_generation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/clock_generation.cpp.s
.PHONY : src/ams/clock_generation.cpp.s

src/ams/dfe_adapt_tdf.o: src/ams/dfe_adapt_tdf.cpp.o
.PHONY : src/ams/dfe_adapt_tdf.o

# target to build an object file
src/ams/dfe_adapt_tdf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/dfe_adapt_tdf.cpp.o
.PHONY : src/ams/dfe_adapt_tdf.cpp.o

src/ams/dfe_adapt_tdf.i: src/ams/dfe_adapt_tdf.cpp.i
.PHONY : src/ams/dfe_adapt_tdf.i

# target to preprocess a source file
src/ams/dfe_adapt_tdf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/dfe_adapt_tdf.cpp.i
.PHONY : src/ams/dfe_adapt_tdf.cpp.i

src/ams/dfe_adapt_tdf.s: src/ams/dfe_adapt_tdf.cpp.s
.PHONY : src/ams/dfe_adapt_tdf.s

# target to generate assembly for a file
src/ams/dfe_adapt_tdf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/dfe_adapt_tdf.cpp.s
.PHONY : src/ams/dfe_adapt_tdf.cpp.s

src/ams/diff_to_single.o: src/ams/diff_to_single.cpp.o
.PHONY : src/ams/diff_to_single.o

# target to build an object file
src/ams/diff_to_single.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/diff_to_single.cpp.o
.PHONY : src/ams/diff_to_single.cpp.o

src/ams/diff_to_single.i: src/ams/diff_to_single.cpp.i
.PHONY : src/ams/diff_to_single.i

# target to preprocess a source file
src/ams/diff_to_single.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/diff_to_single.cpp.i
.PHONY : src/ams/diff_to_single.cpp.i

src/ams/diff_to_single.s: src/ams/diff_to_single.cpp.s
.PHONY : src/ams/diff_to_single.s

# target to generate assembly for a file
src/ams/diff_to_single.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/diff_to_single.cpp.s
.PHONY : src/ams/diff_to_single.cpp.s

src/ams/rx_cdr.o: src/ams/rx_cdr.cpp.o
.PHONY : src/ams/rx_cdr.o

# target to build an object file
src/ams/rx_cdr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_cdr.cpp.o
.PHONY : src/ams/rx_cdr.cpp.o

src/ams/rx_cdr.i: src/ams/rx_cdr.cpp.i
.PHONY : src/ams/rx_cdr.i

# target to preprocess a source file
src/ams/rx_cdr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_cdr.cpp.i
.PHONY : src/ams/rx_cdr.cpp.i

src/ams/rx_cdr.s: src/ams/rx_cdr.cpp.s
.PHONY : src/ams/rx_cdr.s

# target to generate assembly for a file
src/ams/rx_cdr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_cdr.cpp.s
.PHONY : src/ams/rx_cdr.cpp.s

src/ams/rx_ctle.o: src/ams/rx_ctle.cpp.o
.PHONY : src/ams/rx_ctle.o

# target to build an object file
src/ams/rx_ctle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_ctle.cpp.o
.PHONY : src/ams/rx_ctle.cpp.o

src/ams/rx_ctle.i: src/ams/rx_ctle.cpp.i
.PHONY : src/ams/rx_ctle.i

# target to preprocess a source file
src/ams/rx_ctle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_ctle.cpp.i
.PHONY : src/ams/rx_ctle.cpp.i

src/ams/rx_ctle.s: src/ams/rx_ctle.cpp.s
.PHONY : src/ams/rx_ctle.s

# target to generate assembly for a file
src/ams/rx_ctle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_ctle.cpp.s
.PHONY : src/ams/rx_ctle.cpp.s

src/ams/rx_dfe.o: src/ams/rx_dfe.cpp.o
.PHONY : src/ams/rx_dfe.o

# target to build an object file
src/ams/rx_dfe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_dfe.cpp.o
.PHONY : src/ams/rx_dfe.cpp.o

src/ams/rx_dfe.i: src/ams/rx_dfe.cpp.i
.PHONY : src/ams/rx_dfe.i

# target to preprocess a source file
src/ams/rx_dfe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_dfe.cpp.i
.PHONY : src/ams/rx_dfe.cpp.i

src/ams/rx_dfe.s: src/ams/rx_dfe.cpp.s
.PHONY : src/ams/rx_dfe.s

# target to generate assembly for a file
src/ams/rx_dfe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_dfe.cpp.s
.PHONY : src/ams/rx_dfe.cpp.s

src/ams/rx_dfe_summer.o: src/ams/rx_dfe_summer.cpp.o
.PHONY : src/ams/rx_dfe_summer.o

# target to build an object file
src/ams/rx_dfe_summer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_dfe_summer.cpp.o
.PHONY : src/ams/rx_dfe_summer.cpp.o

src/ams/rx_dfe_summer.i: src/ams/rx_dfe_summer.cpp.i
.PHONY : src/ams/rx_dfe_summer.i

# target to preprocess a source file
src/ams/rx_dfe_summer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_dfe_summer.cpp.i
.PHONY : src/ams/rx_dfe_summer.cpp.i

src/ams/rx_dfe_summer.s: src/ams/rx_dfe_summer.cpp.s
.PHONY : src/ams/rx_dfe_summer.s

# target to generate assembly for a file
src/ams/rx_dfe_summer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_dfe_summer.cpp.s
.PHONY : src/ams/rx_dfe_summer.cpp.s

src/ams/rx_sampler.o: src/ams/rx_sampler.cpp.o
.PHONY : src/ams/rx_sampler.o

# target to build an object file
src/ams/rx_sampler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_sampler.cpp.o
.PHONY : src/ams/rx_sampler.cpp.o

src/ams/rx_sampler.i: src/ams/rx_sampler.cpp.i
.PHONY : src/ams/rx_sampler.i

# target to preprocess a source file
src/ams/rx_sampler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_sampler.cpp.i
.PHONY : src/ams/rx_sampler.cpp.i

src/ams/rx_sampler.s: src/ams/rx_sampler.cpp.s
.PHONY : src/ams/rx_sampler.s

# target to generate assembly for a file
src/ams/rx_sampler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_sampler.cpp.s
.PHONY : src/ams/rx_sampler.cpp.s

src/ams/rx_top.o: src/ams/rx_top.cpp.o
.PHONY : src/ams/rx_top.o

# target to build an object file
src/ams/rx_top.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_top.cpp.o
.PHONY : src/ams/rx_top.cpp.o

src/ams/rx_top.i: src/ams/rx_top.cpp.i
.PHONY : src/ams/rx_top.i

# target to preprocess a source file
src/ams/rx_top.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_top.cpp.i
.PHONY : src/ams/rx_top.cpp.i

src/ams/rx_top.s: src/ams/rx_top.cpp.s
.PHONY : src/ams/rx_top.s

# target to generate assembly for a file
src/ams/rx_top.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_top.cpp.s
.PHONY : src/ams/rx_top.cpp.s

src/ams/rx_vga.o: src/ams/rx_vga.cpp.o
.PHONY : src/ams/rx_vga.o

# target to build an object file
src/ams/rx_vga.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_vga.cpp.o
.PHONY : src/ams/rx_vga.cpp.o

src/ams/rx_vga.i: src/ams/rx_vga.cpp.i
.PHONY : src/ams/rx_vga.i

# target to preprocess a source file
src/ams/rx_vga.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_vga.cpp.i
.PHONY : src/ams/rx_vga.cpp.i

src/ams/rx_vga.s: src/ams/rx_vga.cpp.s
.PHONY : src/ams/rx_vga.s

# target to generate assembly for a file
src/ams/rx_vga.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/rx_vga.cpp.s
.PHONY : src/ams/rx_vga.cpp.s

src/ams/serdes_link_top.o: src/ams/serdes_link_top.cpp.o
.PHONY : src/ams/serdes_link_top.o

# target to build an object file
src/ams/serdes_link_top.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/serdes_link_top.cpp.o
.PHONY : src/ams/serdes_link_top.cpp.o

src/ams/serdes_link_top.i: src/ams/serdes_link_top.cpp.i
.PHONY : src/ams/serdes_link_top.i

# target to preprocess a source file
src/ams/serdes_link_top.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/serdes_link_top.cpp.i
.PHONY : src/ams/serdes_link_top.cpp.i

src/ams/serdes_link_top.s: src/ams/serdes_link_top.cpp.s
.PHONY : src/ams/serdes_link_top.s

# target to generate assembly for a file
src/ams/serdes_link_top.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/serdes_link_top.cpp.s
.PHONY : src/ams/serdes_link_top.cpp.s

src/ams/single_to_diff.o: src/ams/single_to_diff.cpp.o
.PHONY : src/ams/single_to_diff.o

# target to build an object file
src/ams/single_to_diff.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/single_to_diff.cpp.o
.PHONY : src/ams/single_to_diff.cpp.o

src/ams/single_to_diff.i: src/ams/single_to_diff.cpp.i
.PHONY : src/ams/single_to_diff.i

# target to preprocess a source file
src/ams/single_to_diff.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/single_to_diff.cpp.i
.PHONY : src/ams/single_to_diff.cpp.i

src/ams/single_to_diff.s: src/ams/single_to_diff.cpp.s
.PHONY : src/ams/single_to_diff.s

# target to generate assembly for a file
src/ams/single_to_diff.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/single_to_diff.cpp.s
.PHONY : src/ams/single_to_diff.cpp.s

src/ams/tx_driver.o: src/ams/tx_driver.cpp.o
.PHONY : src/ams/tx_driver.o

# target to build an object file
src/ams/tx_driver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/tx_driver.cpp.o
.PHONY : src/ams/tx_driver.cpp.o

src/ams/tx_driver.i: src/ams/tx_driver.cpp.i
.PHONY : src/ams/tx_driver.i

# target to preprocess a source file
src/ams/tx_driver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/tx_driver.cpp.i
.PHONY : src/ams/tx_driver.cpp.i

src/ams/tx_driver.s: src/ams/tx_driver.cpp.s
.PHONY : src/ams/tx_driver.s

# target to generate assembly for a file
src/ams/tx_driver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/tx_driver.cpp.s
.PHONY : src/ams/tx_driver.cpp.s

src/ams/tx_ffe.o: src/ams/tx_ffe.cpp.o
.PHONY : src/ams/tx_ffe.o

# target to build an object file
src/ams/tx_ffe.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/tx_ffe.cpp.o
.PHONY : src/ams/tx_ffe.cpp.o

src/ams/tx_ffe.i: src/ams/tx_ffe.cpp.i
.PHONY : src/ams/tx_ffe.i

# target to preprocess a source file
src/ams/tx_ffe.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/tx_ffe.cpp.i
.PHONY : src/ams/tx_ffe.cpp.i

src/ams/tx_ffe.s: src/ams/tx_ffe.cpp.s
.PHONY : src/ams/tx_ffe.s

# target to generate assembly for a file
src/ams/tx_ffe.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/tx_ffe.cpp.s
.PHONY : src/ams/tx_ffe.cpp.s

src/ams/tx_mux.o: src/ams/tx_mux.cpp.o
.PHONY : src/ams/tx_mux.o

# target to build an object file
src/ams/tx_mux.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/tx_mux.cpp.o
.PHONY : src/ams/tx_mux.cpp.o

src/ams/tx_mux.i: src/ams/tx_mux.cpp.i
.PHONY : src/ams/tx_mux.i

# target to preprocess a source file
src/ams/tx_mux.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/tx_mux.cpp.i
.PHONY : src/ams/tx_mux.cpp.i

src/ams/tx_mux.s: src/ams/tx_mux.cpp.s
.PHONY : src/ams/tx_mux.s

# target to generate assembly for a file
src/ams/tx_mux.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/tx_mux.cpp.s
.PHONY : src/ams/tx_mux.cpp.s

src/ams/tx_top.o: src/ams/tx_top.cpp.o
.PHONY : src/ams/tx_top.o

# target to build an object file
src/ams/tx_top.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/tx_top.cpp.o
.PHONY : src/ams/tx_top.cpp.o

src/ams/tx_top.i: src/ams/tx_top.cpp.i
.PHONY : src/ams/tx_top.i

# target to preprocess a source file
src/ams/tx_top.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/tx_top.cpp.i
.PHONY : src/ams/tx_top.cpp.i

src/ams/tx_top.s: src/ams/tx_top.cpp.s
.PHONY : src/ams/tx_top.s

# target to generate assembly for a file
src/ams/tx_top.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/tx_top.cpp.s
.PHONY : src/ams/tx_top.cpp.s

src/ams/wave_generation.o: src/ams/wave_generation.cpp.o
.PHONY : src/ams/wave_generation.o

# target to build an object file
src/ams/wave_generation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/wave_generation.cpp.o
.PHONY : src/ams/wave_generation.cpp.o

src/ams/wave_generation.i: src/ams/wave_generation.cpp.i
.PHONY : src/ams/wave_generation.i

# target to preprocess a source file
src/ams/wave_generation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/wave_generation.cpp.i
.PHONY : src/ams/wave_generation.cpp.i

src/ams/wave_generation.s: src/ams/wave_generation.cpp.s
.PHONY : src/ams/wave_generation.s

# target to generate assembly for a file
src/ams/wave_generation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/ams/wave_generation.cpp.s
.PHONY : src/ams/wave_generation.cpp.s

src/de/config_loader.o: src/de/config_loader.cpp.o
.PHONY : src/de/config_loader.o

# target to build an object file
src/de/config_loader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/de/config_loader.cpp.o
.PHONY : src/de/config_loader.cpp.o

src/de/config_loader.i: src/de/config_loader.cpp.i
.PHONY : src/de/config_loader.i

# target to preprocess a source file
src/de/config_loader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/de/config_loader.cpp.i
.PHONY : src/de/config_loader.cpp.i

src/de/config_loader.s: src/de/config_loader.cpp.s
.PHONY : src/de/config_loader.s

# target to generate assembly for a file
src/de/config_loader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/serdes_lib.dir/build.make CMakeFiles/serdes_lib.dir/src/de/config_loader.cpp.s
.PHONY : src/de/config_loader.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... cdr_tran_tb"
	@echo "... channel_sparam_tb"
	@echo "... ctle_tran_tb"
	@echo "... nrz_link_tb"
	@echo "... sampler_tran_tb"
	@echo "... serdes_lib"
	@echo "... vga_tran_tb"
	@echo "... wave_gen_tran_tb"
	@echo "... src/ams/adaption.o"
	@echo "... src/ams/adaption.i"
	@echo "... src/ams/adaption.s"
	@echo "... src/ams/channel_sparam.o"
	@echo "... src/ams/channel_sparam.i"
	@echo "... src/ams/channel_sparam.s"
	@echo "... src/ams/clock_generation.o"
	@echo "... src/ams/clock_generation.i"
	@echo "... src/ams/clock_generation.s"
	@echo "... src/ams/dfe_adapt_tdf.o"
	@echo "... src/ams/dfe_adapt_tdf.i"
	@echo "... src/ams/dfe_adapt_tdf.s"
	@echo "... src/ams/diff_to_single.o"
	@echo "... src/ams/diff_to_single.i"
	@echo "... src/ams/diff_to_single.s"
	@echo "... src/ams/rx_cdr.o"
	@echo "... src/ams/rx_cdr.i"
	@echo "... src/ams/rx_cdr.s"
	@echo "... src/ams/rx_ctle.o"
	@echo "... src/ams/rx_ctle.i"
	@echo "... src/ams/rx_ctle.s"
	@echo "... src/ams/rx_dfe.o"
	@echo "... src/ams/rx_dfe.i"
	@echo "... src/ams/rx_dfe.s"
	@echo "... src/ams/rx_dfe_summer.o"
	@echo "... src/ams/rx_dfe_summer.i"
	@echo "... src/ams/rx_dfe_summer.s"
	@echo "... src/ams/rx_sampler.o"
	@echo "... src/ams/rx_sampler.i"
	@echo "... src/ams/rx_sampler.s"
	@echo "... src/ams/rx_top.o"
	@echo "... src/ams/rx_top.i"
	@echo "... src/ams/rx_top.s"
	@echo "... src/ams/rx_vga.o"
	@echo "... src/ams/rx_vga.i"
	@echo "... src/ams/rx_vga.s"
	@echo "... src/ams/serdes_link_top.o"
	@echo "... src/ams/serdes_link_top.i"
	@echo "... src/ams/serdes_link_top.s"
	@echo "... src/ams/single_to_diff.o"
	@echo "... src/ams/single_to_diff.i"
	@echo "... src/ams/single_to_diff.s"
	@echo "... src/ams/tx_driver.o"
	@echo "... src/ams/tx_driver.i"
	@echo "... src/ams/tx_driver.s"
	@echo "... src/ams/tx_ffe.o"
	@echo "... src/ams/tx_ffe.i"
	@echo "... src/ams/tx_ffe.s"
	@echo "... src/ams/tx_mux.o"
	@echo "... src/ams/tx_mux.i"
	@echo "... src/ams/tx_mux.s"
	@echo "... src/ams/tx_top.o"
	@echo "... src/ams/tx_top.i"
	@echo "... src/ams/tx_top.s"
	@echo "... src/ams/wave_generation.o"
	@echo "... src/ams/wave_generation.i"
	@echo "... src/ams/wave_generation.s"
	@echo "... src/de/config_loader.o"
	@echo "... src/de/config_loader.i"
	@echo "... src/de/config_loader.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

