/**
 * @file test_sparam_load.cpp
 * @brief S-parameter JSON config loading verification test
 * 
 * Tests verify that C++ ChannelSParamTdf correctly loads and parses
 * configuration generated by Python preprocessing script.
 * This is Batch 1 verification test.
 */

#include <gtest/gtest.h>
#include <systemc-ams>
#include <fstream>
#include <iostream>

#include "common/parameters.h"
#include "ams/channel_sparam.h"

namespace serdes {
namespace test {

// Path to test configuration files (generated by Python)
static const char* RATIONAL_CONFIG_PATH = "../test_config_rational.json";
static const char* IMPULSE_CONFIG_PATH = "../test_config_impulse.json";

/**
 * Test fixture for S-parameter config loading tests
 */
class SParamLoadTest : public ::testing::Test {
protected:
    void SetUp() override {
        // Check if test config files exist
        std::ifstream fr(RATIONAL_CONFIG_PATH);
        rational_exists_ = fr.good();
        fr.close();
        
        std::ifstream fi(IMPULSE_CONFIG_PATH);
        impulse_exists_ = fi.good();
        fi.close();
    }
    
    bool rational_exists_ = false;
    bool impulse_exists_ = false;
};

/**
 * Test that rational config file exists
 */
TEST_F(SParamLoadTest, RationalConfigFileExists) {
    ASSERT_TRUE(rational_exists_) 
        << "Rational config file not found: " << RATIONAL_CONFIG_PATH
        << "\nRun: python scripts/process_sparam.py -m rational to generate it";
}

/**
 * Test that impulse config file exists
 */
TEST_F(SParamLoadTest, ImpulseConfigFileExists) {
    ASSERT_TRUE(impulse_exists_) 
        << "Impulse config file not found: " << IMPULSE_CONFIG_PATH
        << "\nRun: python scripts/process_sparam.py -m impulse to generate it";
}

/**
 * Test loading rational config via ChannelSParamTdf
 */
TEST_F(SParamLoadTest, LoadRationalConfig) {
    if (!rational_exists_) {
        GTEST_SKIP() << "Rational config file not available";
    }
    
    std::cout << "\n=== Testing Rational Config Loading ===" << std::endl;
    
    // Create channel with extended params
    ChannelParams params;
    params.attenuation_db = 0.0;
    params.bandwidth_hz = 10e9;
    
    ChannelExtendedParams ext_params;
    ext_params.config_file = RATIONAL_CONFIG_PATH;
    ext_params.fs = 100e9;
    
    // Create module
    ChannelSParamTdf channel("channel", params, ext_params);
    
    // Verify method was set correctly
    EXPECT_EQ(channel.get_method(), ChannelMethod::RATIONAL);
    
    // Verify DC gain is loaded
    double dc_gain = channel.get_dc_gain();
    std::cout << "DC Gain: " << dc_gain << std::endl;
    EXPECT_GT(dc_gain, 0.0);
    EXPECT_LT(dc_gain, 2.0);
    
    std::cout << "=== Rational Config Loading PASSED ===" << std::endl;
}

/**
 * Test loading impulse config via ChannelSParamTdf
 */
TEST_F(SParamLoadTest, LoadImpulseConfig) {
    if (!impulse_exists_) {
        GTEST_SKIP() << "Impulse config file not available";
    }
    
    std::cout << "\n=== Testing Impulse Config Loading ===" << std::endl;
    
    // Create channel with extended params
    ChannelParams params;
    params.attenuation_db = 0.0;
    params.bandwidth_hz = 10e9;
    
    ChannelExtendedParams ext_params;
    ext_params.config_file = IMPULSE_CONFIG_PATH;
    ext_params.fs = 100e9;
    
    // Create module
    ChannelSParamTdf channel("channel", params, ext_params);
    
    // Verify method was set correctly
    EXPECT_EQ(channel.get_method(), ChannelMethod::IMPULSE);
    
    // Verify DC gain is loaded
    double dc_gain = channel.get_dc_gain();
    std::cout << "DC Gain: " << dc_gain << std::endl;
    EXPECT_GT(dc_gain, 0.0);
    EXPECT_LT(dc_gain, 2.0);
    
    std::cout << "=== Impulse Config Loading PASSED ===" << std::endl;
}

/**
 * Test loading config manually via load_config()
 */
TEST_F(SParamLoadTest, ManualLoadConfig) {
    if (!rational_exists_) {
        GTEST_SKIP() << "Rational config file not available";
    }
    
    std::cout << "\n=== Testing Manual Config Loading ===" << std::endl;
    
    // Create channel without config file
    ChannelParams params;
    params.attenuation_db = 0.0;
    params.bandwidth_hz = 10e9;
    
    ChannelSParamTdf channel("channel", params);
    
    // Initially should be SIMPLE method
    EXPECT_EQ(channel.get_method(), ChannelMethod::SIMPLE);
    
    // Load config manually
    bool result = channel.load_config(RATIONAL_CONFIG_PATH);
    EXPECT_TRUE(result) << "Failed to load config file";
    
    // Now should be RATIONAL method
    EXPECT_EQ(channel.get_method(), ChannelMethod::RATIONAL);
    
    std::cout << "=== Manual Config Loading PASSED ===" << std::endl;
}

/**
 * Test loading non-existent config file
 */
TEST_F(SParamLoadTest, LoadNonExistentConfig) {
    std::cout << "\n=== Testing Non-Existent Config Loading ===" << std::endl;
    
    ChannelParams params;
    ChannelSParamTdf channel("channel", params);
    
    // Try to load non-existent file
    bool result = channel.load_config("non_existent_file.json");
    EXPECT_FALSE(result) << "Should fail to load non-existent file";
    
    std::cout << "=== Non-Existent Config Loading PASSED ===" << std::endl;
}

} // namespace test
} // namespace serdes

// SystemC main function
int sc_main(int argc, char **argv) {
    // Suppress SystemC warnings
    sc_core::sc_report_handler::set_actions("/IEEE_Std_1666/deprecated", sc_core::SC_DO_NOTHING);
    
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
