/**
 * @file test_sparam_load_simple.cpp
 * @brief S-parameter JSON config loading verification test (simple version)
 * 
 * Tests verify that C++ ChannelSParamTdf correctly loads and parses
 * configuration generated by Python preprocessing script.
 * This is Batch 1 verification test - no GTest dependency.
 */

#include <systemc-ams>
#include <fstream>
#include <iostream>
#include <cstdlib>

#include "common/parameters.h"
#include "ams/channel_sparam.h"

using namespace serdes;

// Path to test configuration files (generated by Python)
static const char* RATIONAL_CONFIG_PATH = "../test_config_rational.json";
static const char* IMPULSE_CONFIG_PATH = "../test_config_impulse.json";

// Test result tracking
int tests_passed = 0;
int tests_failed = 0;

#define TEST_ASSERT(condition, message) \
    do { \
        if (!(condition)) { \
            std::cerr << "[FAIL] " << message << " at line " << __LINE__ << std::endl; \
            tests_failed++; \
            return false; \
        } \
    } while(0)

#define TEST_PASS(message) \
    do { \
        std::cout << "[PASS] " << message << std::endl; \
        tests_passed++; \
        return true; \
    } while(0)

// Check if file exists
bool file_exists(const char* path) {
    std::ifstream f(path);
    bool exists = f.good();
    f.close();
    return exists;
}

// Test: Rational config file exists
bool test_rational_config_exists() {
    std::cout << "\n=== Test: Rational Config File Exists ===" << std::endl;
    bool exists = file_exists(RATIONAL_CONFIG_PATH);
    if (!exists) {
        std::cerr << "[FAIL] Rational config file not found: " << RATIONAL_CONFIG_PATH << std::endl;
        tests_failed++;
        return false;
    }
    std::cout << "[PASS] Rational config file found: " << RATIONAL_CONFIG_PATH << std::endl;
    tests_passed++;
    return true;
}

// Test: Impulse config file exists
bool test_impulse_config_exists() {
    std::cout << "\n=== Test: Impulse Config File Exists ===" << std::endl;
    bool exists = file_exists(IMPULSE_CONFIG_PATH);
    if (!exists) {
        std::cerr << "[FAIL] Impulse config file not found: " << IMPULSE_CONFIG_PATH << std::endl;
        tests_failed++;
        return false;
    }
    std::cout << "[PASS] Impulse config file found: " << IMPULSE_CONFIG_PATH << std::endl;
    tests_passed++;
    return true;
}

// Test: Load rational config via ChannelSParamTdf
bool test_load_rational_config() {
    std::cout << "\n=== Test: Load Rational Config ===" << std::endl;
    
    if (!file_exists(RATIONAL_CONFIG_PATH)) {
        std::cout << "[SKIP] Rational config file not available" << std::endl;
        return true;
    }
    
    // Create channel with extended params
    ChannelParams params;
    params.attenuation_db = 0.0;
    params.bandwidth_hz = 10e9;
    
    ChannelExtendedParams ext_params;
    ext_params.config_file = RATIONAL_CONFIG_PATH;
    ext_params.fs = 100e9;
    
    // Create module
    ChannelSParamTdf channel("channel", params, ext_params);
    
    // Verify method was set correctly
    if (channel.get_method() != ChannelMethod::RATIONAL) {
        std::cerr << "[FAIL] Method should be RATIONAL" << std::endl;
        tests_failed++;
        return false;
    }
    
    // Verify DC gain is loaded
    double dc_gain = channel.get_dc_gain();
    std::cout << "  DC Gain: " << dc_gain << std::endl;
    if (dc_gain <= 0.0 || dc_gain >= 2.0) {
        std::cerr << "[FAIL] DC gain out of range: " << dc_gain << std::endl;
        tests_failed++;
        return false;
    }
    
    std::cout << "[PASS] Rational config loaded successfully" << std::endl;
    tests_passed++;
    return true;
}

// Test: Load impulse config via ChannelSParamTdf
bool test_load_impulse_config() {
    std::cout << "\n=== Test: Load Impulse Config ===" << std::endl;
    
    if (!file_exists(IMPULSE_CONFIG_PATH)) {
        std::cout << "[SKIP] Impulse config file not available" << std::endl;
        return true;
    }
    
    // Create channel with extended params
    ChannelParams params;
    params.attenuation_db = 0.0;
    params.bandwidth_hz = 10e9;
    
    ChannelExtendedParams ext_params;
    ext_params.config_file = IMPULSE_CONFIG_PATH;
    ext_params.fs = 100e9;
    
    // Create module
    ChannelSParamTdf channel("channel", params, ext_params);
    
    // Verify method was set correctly
    if (channel.get_method() != ChannelMethod::IMPULSE) {
        std::cerr << "[FAIL] Method should be IMPULSE" << std::endl;
        tests_failed++;
        return false;
    }
    
    // Verify DC gain is loaded
    double dc_gain = channel.get_dc_gain();
    std::cout << "  DC Gain: " << dc_gain << std::endl;
    if (dc_gain <= 0.0 || dc_gain >= 2.0) {
        std::cerr << "[FAIL] DC gain out of range: " << dc_gain << std::endl;
        tests_failed++;
        return false;
    }
    
    std::cout << "[PASS] Impulse config loaded successfully" << std::endl;
    tests_passed++;
    return true;
}

// Test: Manual load config via load_config()
bool test_manual_load_config() {
    std::cout << "\n=== Test: Manual Load Config ===" << std::endl;
    
    if (!file_exists(RATIONAL_CONFIG_PATH)) {
        std::cout << "[SKIP] Rational config file not available" << std::endl;
        return true;
    }
    
    // Create channel without config file
    ChannelParams params;
    ChannelSParamTdf channel("channel", params);
    
    // Initially should be SIMPLE method
    if (channel.get_method() != ChannelMethod::SIMPLE) {
        std::cerr << "[FAIL] Initial method should be SIMPLE" << std::endl;
        tests_failed++;
        return false;
    }
    
    // Load config manually
    bool result = channel.load_config(RATIONAL_CONFIG_PATH);
    if (!result) {
        std::cerr << "[FAIL] Failed to load config file" << std::endl;
        tests_failed++;
        return false;
    }
    
    // Now should be RATIONAL method
    if (channel.get_method() != ChannelMethod::RATIONAL) {
        std::cerr << "[FAIL] Method should be RATIONAL after loading" << std::endl;
        tests_failed++;
        return false;
    }
    
    std::cout << "[PASS] Manual config loading works" << std::endl;
    tests_passed++;
    return true;
}

// Test: Load non-existent config file
bool test_load_nonexistent_config() {
    std::cout << "\n=== Test: Load Non-Existent Config ===" << std::endl;
    
    ChannelParams params;
    ChannelSParamTdf channel("channel", params);
    
    // Try to load non-existent file
    bool result = channel.load_config("non_existent_file.json");
    if (result) {
        std::cerr << "[FAIL] Should fail to load non-existent file" << std::endl;
        tests_failed++;
        return false;
    }
    
    std::cout << "[PASS] Non-existent file correctly rejected" << std::endl;
    tests_passed++;
    return true;
}

// SystemC main function
int sc_main(int argc, char **argv) {
    // Suppress SystemC warnings
    sc_core::sc_report_handler::set_actions("/IEEE_Std_1666/deprecated", sc_core::SC_DO_NOTHING);
    
    std::cout << "========================================" << std::endl;
    std::cout << "Batch 1: S-Parameter Config Loading Test" << std::endl;
    std::cout << "========================================" << std::endl;
    
    // Run all tests
    test_rational_config_exists();
    test_impulse_config_exists();
    test_load_rational_config();
    test_load_impulse_config();
    test_manual_load_config();
    test_load_nonexistent_config();
    
    // Print summary
    std::cout << "\n========================================" << std::endl;
    std::cout << "Test Summary:" << std::endl;
    std::cout << "  Passed: " << tests_passed << std::endl;
    std::cout << "  Failed: " << tests_failed << std::endl;
    std::cout << "========================================" << std::endl;
    
    return tests_failed > 0 ? 1 : 0;
}
